language: ruby
rvm:
  - 2.0.0
services:
  - postgresql
  - elasticsearch
notifications:
  webhooks: http://deploy.holderdeord.no/travis
  recipients:
    - jari@holderdeord.no
  hipchat:
    rooms:
      secure: "dPDcvtGQXXzdj31ftZkRShrn+l1TCnTEPTdr6YVAfzAI1Ashzhr4yGvnNfMs\n4lbxYDJfRxpTO5Xd1Hte5HH7c0ijoHEGjajySSl43+nLeShw+CWhuxKSbmCM\nnICGbjLhNPSDTIg1QPO/AkUCF3YG6szmd3JX9XLathUrt0HOBTY="
    on_success: always
    on_failure: always
  template:
    - "%{author} | %{commit} | %{message} | %{build_url}"
  irc:
    channels:
      - "irc.freenode.net#holderdeord"
    on_success: change
    on_failure: change
    template:
      - "%{author} | %{commit} | %{message} | %{build_url}"
bundler_args: --without development --path ~/.bundle
script: "RAILS_ENV=test SPEC_OPTS=--backtrace bundle exec rake travis"
before_install:
  - ./script/travis/bundle_download.sh
before_script:
  - dpkg -s elasticsearch | grep --color=never Version
  - mv config/database.yml.travis config/database.yml
  - sh -e /etc/init.d/xvfb start
  - ./script/travis/npm_bootstrap.sh
after_script:
  - ./script/travis/bundle_cache.sh
env:
  global:
    - secure: "PSyNsqaahsPzmTbjo+tAOZONgXDcWYomETnk+fFnqTBNFhkR9v+fAzIc2drD\nHn2QHd26TfmCN7YJtn7b57RwQ/TN2V4WVRI6TLC6BaIGLbj7HJpnR8rb37U9\nxo/HYULBAK/McwnaVOS6d6EmaI+jvHNDAeUd9NfH2tVx74C2qSU="
    - DISPLAY=:99.0
    - COVERAGE_THRESHOLD=83
    - RUBY_GC_MALLOC_LIMIT=50000000
