defaults: &defaults
  elasticsearch_url: <%= ENV['ELASTICSEARCH_URL'] || ENV['BONSAI_URL'] || 'http://localhost:9200' %>
  basic_auth_users: <%= ENV['HDO_BASIC_AUTH'] || '' %>
  hipchat_api_token: <%= ENV['HIPCHAT_API_TOKEN'] || '' %>
  question_answer_email: sporsmalsvar@holderdeord.no
  default_bcc_email: test@holderdeord.no
  default_reply_to_email: sporsmalsvar@holderdeord.no
  twitter_widget_id: '316893415021363200'
  statsd_host: 5.9.122.47 # ops1.holderdeord.no, but avoid DNS lookup
  statsd_port: 8125
  statsd_enabled: false
  read_only: false
  front_page_search_enabled: true
  fastly_enabled: false
  ssl_enabled: false
  ssl_host: ~
  analytics_enabled: false
  show_accountability: true
  widgets_enabled: true
  weights_enabled: true
  chat_notifications_enabled: false
  ignore_votes_against_alternate_budget: true
  topic_of_the_week: Samferdsel

development:
  <<: *defaults
  basic_auth_users: 'test:test'

test:
  <<: *defaults
  basic_auth_users: 'test:test'

staging:
  <<: *defaults
  statsd_enabled: true
  fastly_enabled: true
  ssl_enabled: true
  chat_notifications_enabled: true

production:
  <<: *defaults
  statsd_enabled: true
  analytics_enabled: true
  fastly_enabled: true
  ssl_enabled: true
  default_bcc_email: prodcopy@holderdeord.no
  chat_notifications_enabled: true
